### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by anbraten** [janelucia/portfolio#1]
Haven't seen a deployment of the page yet. Maybe you want to give https://vercel.com/ a try.

**Comment by janelucia** [comment]
@anbraten I will keep it in mind - thank you

**Comment by anbraten** [comment]
It's just one button click away and will even create review environments for PRs, so can just recommend to you to enable it quickly sooner than later 😉

**Comment by anbraten** [comment]
The deployment looks awesome already. Great job and thanks for sharing.
